name: publish

on:
  push:
    tags: ['[0-9]+.[0-9]+.[0-9]+']

jobs:
  publish:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build the image
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        VERSION=$(echo "${GITHUB_REF}" | cut -d "/" -f3)
        echo "Building version ${VERSION}"
        echo $GITHUB_TOKEN | docker login ghcr.io -u axetrading --password-stdin
        docker build . --tag ghcr.io/axetrading/s3-downloader:${VERSION}
        docker push ghcr.io/axetrading/s3-downloader:${VERSION