name: publish

on:
  push:
    tags: ['[0-9]+.[0-9]+.[0-9]+']

jobs:
  publish:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21'

      - name: Download Go modules
        run: |
          go mod download

      - name: Build binary
        run: |
          VERSION=$(echo "${GITHUB_REF}" | cut -d "/" -f3)
          echo "Building binary version ${VERSION}"
          CGO_ENABLED=0 GOOS=linux go build -o s3-downloader

      - name: Deploy artifacts
        uses: actions/upload-artifact@v2
        with:
          name: s3-downloader
          path: s3-downloader

      - name: Log in to GitHub Container Registry
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo $GITHUB_TOKEN | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Build and push Docker image
        run: |
          VERSION=$(echo "${GITHUB_REF}" | cut -d "/" -f3)
          echo "Building Docker image version ${VERSION}"
          docker build . --tag ghcr.io/${{ github.repository_owner }}/s3-downloader:${VERSION}
          docker push ghcr.io/${{ github.repository_owner }}/s3-downloader:${VERSION}
