name: publish

on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build the image
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo $GITHUB_TOKEN | docker login ghcr.io -u axetrading --password-stdin
        docker build . --tag ghcr.io/axetrading/s3-downloader:latest
        docker push ghcr.io/axetrading/s3-downloader:latest